version: '3'
services:
  locust-master:
    build: .
    command: locust -f main.py -H 10.50.11.160:30002 --master
    volumes: 
      - .:/usr/src/app
    ports:
      - 8089:8089
  locust-slave:
    build: .
    command: locust -f main.py --slave --master-host=locust-master
    volumes: 
      - .:/usr/src/app
    depends_on:
      - locust-master
  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
